services:
  - type: web
    name: stylish-employee-attendance
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: logs
      mountPath: /var/www/flask_app/logs
      sizeGB: 1

databases:
  - name: attendance-db
    databaseName: attendance
    user: attendance_user
    plan: free 