services:
  - type: web
    name: stylish-employee-attendance
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: cd /opt/render/project/src && gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: wsgi.py
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: logs
      mountPath: /var/www/flask_app/logs
      sizeGB: 1

databases:
  - name: attendance-db
    databaseName: attendance
    user: attendance_user
    plan: free 